### ISSUE TITLE
Selecting another namespace with Microsoft Edge doesn't work?

### ISSUE THREAD

**Issue by mathieu-benoit** [benc-uk/kubeview#12]
With Microsoft Edge, if I change the namespace from `default` to another one, I'm not able to get it working, Tab or Enter to lose the focus will get back to the `default` namespace. 

With Google Chrome, as soon as I select another namespace in the dropdown, the main view is refreshed.

Are you able to reproduce it?

**Comment by benc-uk** [comment]
If you're using classic Edge, it doesn't work. I use a HTML5 element `datalist` which Edge has poor support for.
In new Chrome Edge it works fine, seeing as classic Edge is going to be phased out soon AFAIK, I don't think it's a big problem

**Comment by mathieu-benoit** [comment]
Oh ok good to know, thanks.
