### ISSUE TITLE
Feature Request: Namespace scope instead of cluster wide

### ISSUE THREAD

**Issue by mkilchhofer** [benc-uk/kubeview#17]
Hi

I find this application quite useful. On my homelab k3s-cluster where I am the cluster admin I can deploy this app cluster wide. But in a shared cluster from a PaaS provider it is not possible to add a ClusterRole and a ClusterRoleBinding. So i made a little hack in a helm chart and replaced ClusterRole with Role and ClusterRoleBinding with RoleBinding:
https://github.com/cowboysysop/charts/pull/14

The only little issues now occur:
* when I launch the app in the browser, it tries to display the `default`-Namespace, where it has no permissions
* the app tries to ask the k8s api-server what namspaces are available which will also fail since we have no permissions to list namespaces

Would it be a big effort to add the ability to only display the current namespace where the app is deployed in?

Cheers!
Marco

**Comment by benc-uk** [comment]
This is a great suggestion and something I hadn't considered
I think passing a USE_NAMESPACE environmental variable to the container and have it use that and change behavior accordingly. Then have the Helm chart control passing that it in or not, plus creating a Role and RoleBindings instead.

I'll definitely look into this

**Comment by benc-uk** [comment]
Added in release https://github.com/benc-uk/kubeview/releases/tag/0.1.11

Let me know if it meets your requirement and works for you. See the updated Helm chart and docs for more details

I'll close this for now

**Comment by mkilchhofer** [comment]
Hi Ben

Thanks you so much for the quick implementation of my request :+1: 
I already deployed it using your helm chart and I am happy with it.

I also noticed that you now build container images with an exact version - I almost opened another feature request for this.

Cheers!
Marco
