### ISSUE TITLE
Search namespaces using dropdown

### ISSUE THREAD

**Issue by ffahri** [benc-uk/kubeview#2]
Its brokes view if you have a lot of namespaces by clicking namespace dropdown button. Also it would be nice to refine namespace by writing first letters.

**Comment by benc-uk** [comment]
I certainly never tested this with a large number of namespaces, so it's likely the UI does degrade

A filter on the drop-down is a good idea

**Comment by benc-uk** [comment]
Fix in 025c237afcf86319c76bb18422e0ad6a5d7b53fa
