### ISSUE TITLE
Upgrading to v0.1.11 throws a not found error (.kube/config: no such file or directory)

### ISSUE THREAD

**Issue by cristian04** [benc-uk/kubeview#21]
After updating to v0.1.11 with `kubectl set image` the new pods were crashing due to an error with the k8s configuration.

It seems to be related to the removal of `IN_CLUSTER=true` in the Dockerfile.

I will perform additional diagnostics and add the info here.

Log: 
```
2020/03/12 13:30:17 ### Kubeview v0.1.11 starting...
2020/03/12 13:30:17 ### Connecting to Kubernetes...
2020/03/12 13:30:17 ### Creating client with config file: /.kube/config
panic: stat /.kube/config: no such file or directory

goroutine 1 [running]:
main.main()
	/build/cmd/server/main.go:59 +0xc54
```

PS: Thanks for all the upgrades! Great stuff! 👏

**Comment by cristian04** [comment]
Fixed by adding 

```
name: IN_CLUSTER
              value: "true"
```

**Note**: " " are required has these are required as per https://github.com/kubernetes/kubernetes/issues/73692

**Comment by benc-uk** [comment]
Hi, Sorry yes I felt that having that hard coded int he Dockerfile was a bit hidden and easy to miss.
I updated the Helm chart to include it but made a typo, you're correct the true should be in quotes
