### ISSUE TITLE
Secret content is still visible via annotation

### ISSUE THREAD

**Issue by adidenko** [benc-uk/kubeview#25]
Although secrets' content is `__VALUE REDACTED__`, it's still possible to see full secret in the `kubectl.kubernetes.io/last-applied-configuration` annotation. It probably makes sense to simply drop this annotation from the full object view for `Secret`.

**Comment by scottc-git** [comment]
Wow.. this is a deal breaker.  Otherwise, I love Kubeview.   Nice work guys!

**Comment by benc-uk** [comment]
Good catch, sound be an easy fix, `last-applied-configuration` is rarely interesting so filtering it out is no big loss. I have a branch on the go with some other changes I'll add it to that

**Comment by benc-uk** [comment]
Fixed in 0.1.15 just released

Thanks for bringing this to my attention

![image](https://user-images.githubusercontent.com/14982936/78534736-d484ab00-77e2-11ea-9be1-f1a0d43e9059.png)
