### ISSUE TITLE
do not show all pods

### ISSUE THREAD

**Issue by Perfect-Web** [benc-uk/kubeview#28]
Hi,

Would it be possible not to show all pods under a statefulset or deployment ? 
It can get messy if i try to plot a diagram of a deployment with 10 pods, just showing the deployment icon there (eventually with a double click on it to expand the underneath pods) would suffice

**Comment by darjisanket** [comment]
Yes, We have 200 pods and it little messy to undrand graph with 40+ deployments.

**Comment by benc-uk** [comment]
The filter feature allows you to remove pods from the view
