### ISSUE TITLE
UI gets stuck when loading entrypoint

### ISSUE THREAD

**Issue by JonnyLewis** [benc-uk/kubeview#29]
When the ui tries to load entrypoint the load bar gets stuck and does not format and sort the UI.

![Screen Shot 2020-04-09 at 5 13 23 PM](https://user-images.githubusercontent.com/30020396/78910553-71667300-7a85-11ea-9354-1c8911890f1a.png)

when viewing the console we see the following:

![Screen Shot 2020-04-09 at 5 10 15 PM](https://user-images.githubusercontent.com/30020396/78910501-5b58b280-7a85-11ea-8449-d9d2bac20dd3.png)

When digging into the console i see the following:

message: "Can not create second element with ID `ConfigMap_wso2am-pattern-2-conf-entrypoint`"

**Comment by sohnaeo** [comment]
@benc-uk 

It is great tool but I am having the same issues, for few namespaces load bar gets stuck and does not format and sort the UI. All the objects overlap each other. Is there any plan to fix this?

**Comment by benc-uk** [comment]
I can not reproduce this, much less fix it, without more information 
Do you also see the "Can not create second element" error?

**Comment by sohnaeo** [comment]
@benc-uk 

It works great for some namespaces but for some namespaces, it shows blank screen, I captured the errors through F12, and then you have to drag object from the left and then keep dragging to see all the objects. Its great product if you can fix this bug, I believe few other users also facing the same issue.
![Screenshot from 2020-08-27 15-36-19](https://user-images.githubusercontent.com/50693992/91389075-f22edb80-e87b-11ea-97a0-27a51e21974c.png)
![Screenshot from 2020-08-27 15-36-40](https://user-images.githubusercontent.com/50693992/91389088-f65af900-e87b-11ea-85cd-e7854fa97963.png)
![Screenshot from 2020-08-27 15-38-11](https://user-images.githubusercontent.com/50693992/91389101-f955e980-e87b-11ea-97fd-86f71e93f7a0.png)
