### ISSUE TITLE
Replicasets with no running pods show empty box

### ISSUE THREAD

**Issue by REBELinBLUE** [benc-uk/kubeview#3]
If you have revision history on a deployment kubernetes keeps X previous replicasets and 0 pods.

So in kubeview you get the black box which pods are shown in but it is empty and looks like a tiny square.

I am having a look to figure out if it would be possible to only add the group when adding the first node but I am reporting this in case I fail...

**Comment by benc-uk** [comment]
This has annoyed me too, I've tweaked the display logic to skip over any sets that have 0 replicas.  
I don't think there will be any side effects to this

Fixed with: 52ae45b82a795ab0326b2fab4a47610f5d975dd7

**Comment by REBELinBLUE** [comment]
Completely forgot about this, never got round to actually looking into it to do a PR so thanks :)

**Comment by benc-uk** [comment]
No worries! I only just found there was people submitting issues here! GitHub doesn't seem to notify you of new issues, on repos you create/own, which is really strange

**Comment by REBELinBLUE** [comment]
I think this might be slightly better

```if(obj.status.replicas == 0 || obj.status.desiredNumberScheduled == 0) continue;```

I have a daemonset which currently doesn't match any nodes, so it display the blank box because daemonsets don't have the replicas property.

Or possibly `currentNumberScheduled `but I guess not as that wouldn't quite be the same behaviour as `replicas`
