### ISSUE TITLE
Make helm chart available via a repository (artifacthub.io and hub.helm.sh)

### ISSUE THREAD

**Issue by mkilchhofer** [benc-uk/kubeview#35]
It would be nice if you could package your helm chart as *.tgz and make it available through one of these portals:
- https://artifacthub.io/packages/search?page=1&ts_query_web=kubeview
- https://hub.helm.sh/

When this takes too much time it would be nice to upload it at least as a release tgz-package to the releases section here on GitHub.

**Comment by benc-uk** [comment]
I've now made the chart available as part of the release here
https://github.com/benc-uk/kubeview/releases/tag/0.1.17

As for those other portals I don't know who uploaded my chart there, it wasn't me but I'll take a look

**Comment by benc-uk** [comment]
Also on Artifacthub 
https://artifacthub.io/packages/helm/kubeview/kubeview
