### ISSUE TITLE
Add support for loadBalancerIP in helm chart

### ISSUE THREAD

**Issue by FlipEnergy** [benc-uk/kubeview#39]
Some load balancer services such as MetalLB support specifying an external IP for the service. I'd like the chart to support it.

Based on the way your chart is written, since there's no service section, I guess it can just go straight in the root of the values file.

**Comment by benc-uk** [comment]
Makes sense, I've used LoadBalancerIP in cloud deployments too (so my LB IP is fixed static and not re-assigned by the cloud provider)
