### ISSUE TITLE
Pods without owner causes error

### ISSUE THREAD

**Issue by REBELinBLUE** [benc-uk/kubeview#4]
For example in the `kube-system` namespace `etcd-master` isn't part of a ReplicaSet, DaemonSet or StatefulSet so you get an error

```TypeError: Cannot read property '0' of undefined```

caused by

```        let owner = pod.metadata.ownerReferences[0];```

It looks like further down you do check if ownerReferences is set before using it

```for(let ownerRef of pod.metadata.ownerReferences || []) {```

**Comment by benc-uk** [comment]
Good spot. I never tested this with any "naked" pods.

Fixed by f85c69e462fb87e6e1115299bf24354aeae60e37
