### ISSUE TITLE
Release 0.1.18 helm chart package issues

### ISSUE THREAD

**Issue by FlipEnergy** [benc-uk/kubeview#42]
Noticed some issues with your latest release which included a packaged helm chart.
1. the chart version is 0.0.0 in charts.yaml.
2. app version is still 0.1.17
3. values.yaml specify tag 0.1.17

**Comment by tomkerkhove** [comment]
https://github.com/benc-uk/kubeview/pull/43 fixes the app version.

**Comment by benc-uk** [comment]
Thanks guys, I've fixed this now, and manually fixed the version attached to the release in GitHub
