### ISSUE TITLE
Icon for ReplicaSets missing from v1.1.18

### ISSUE THREAD

**Issue by FlipEnergy** [benc-uk/kubeview#45]
The icon for replicaset is not found in the image it appears. The for the icon at path `img/res/rs-grey.svg` is returning a 404:

![image](https://user-images.githubusercontent.com/7714381/104966586-1eb3d300-5996-11eb-82b5-d67b91db5233.png)

I did a sanity check in the repo for this file in the repo and it doesn't appear to be there on master branch either.

**Comment by benc-uk** [comment]
Thanks for spotting.

Fixed in PR #46 and release 0.1.19
