### ISSUE TITLE
Hide Secrets

### ISSUE THREAD

**Issue by sohnaeo** [benc-uk/kubeview#50]
Hi,

I just thought to give you some feedback about this project, great tool. Currently, I am using 1.17 version and in this version I can remove secrets from the clusterrole and app works fine. I dont want to display secrets because secrets are in base64 and anyone can decode easily.

But new version 1.20 , if I remove secret from clusterrole I get below errors

2021/02/09 23:29:36 ### 10.243.167.1 GET /api/scrape/smoketest
2021/02/09 23:29:36 ### Kubernetes API error secrets is forbidden: User "system:serviceaccount:kubeview:kubeview-helm-kubeview" cannot list resource "secrets" in API group "" in the namespace "smoketest"

Could you please fix this in all new versions? As I said, it is working fine in 1.17 if I remove secret from the clusterrole. 

Secondly, it would be great if pods logs can be displayed as well, feature request.

**Comment by benc-uk** [comment]
Secrets are not exposed by the Kubeview API, they are obfuscated before being sent, so the base64 string you actually see from the API are in fact the value "__VALUE REDACTED__" 

https://github.com/benc-uk/kubeview/blob/3cec78dc8c3a7a1a46637aa430214ac0ad040416/cmd/server/routes.go#L227

**Comment by sohnaeo** [comment]
Ah great, sorry I should have checked :), all good

It is very nice tool. If you provide the pod logs that would be awsome
