### ISSUE TITLE
Discussion: Chart releasing (use gh-pages branch)

### ISSUE THREAD

**Issue by mkilchhofer** [benc-uk/kubeview#56]
Hi

I noticed the `*.tgz` files inside `/charts` directory (https://github.com/benc-uk/kubeview/tree/master/charts). Do you use the GitHub Pages feature for this repository (especially the branch `gh-pages`)?
Is there a reason, why you don't use a separate GitHub Action for this? Eg. you could use the [helm-chart-releaser](https://github.com/marketplace/actions/helm-chart-releaser?version=v1.2.0) action.

**Comment by benc-uk** [comment]
Hi,
It's because the repo is indexed by Artifact Hub https://artifacthub.io/packages/helm/kubeview/kubeview

It is done via GitHub actions here https://github.com/benc-uk/kubeview/blob/master/.github/workflows/docker-release.yml
I use actions/upload-release-asset@v1 to push the tgz file back into the repo

**Comment by mkilchhofer** [comment]
Yup, but the `*.tgz` are also available inside the releases and can be downloaded through a url like
```
https://github.com/<user>/<project>/releases/download/<releaseName>/<artifact>.tgz
```

You could put that in the [index.yaml](https://github.com/benc-uk/kubeview/blob/master/charts/index.yaml#L17). Instead of specifying a relative *.tgz, you could do:
```diff
    urls:
-    - kubeview-0.1.20.tgz
+    - https://github.com/benc-uk/kubeview/releases/download/0.1.20/kubeview-0.1.20.tgz
```

The mentioned action would do this for you :)

**Comment by benc-uk** [comment]
Thanks
I'm happy with how it's set up, it's working ok. Not broken so I don't want to fix.
