### ISSUE TITLE
non / path Ingress causing failures

### ISSUE THREAD

**Issue by kaladinstorm84** [benc-uk/kubeview#65]
When the nginx Ingress path is not set to root , when the page loads calls to <host>/api/scrape/default are failing as they should be getting directed to <host>/<path>/api/scrape/default. 

setting environment variable  VUE_APP_API_ENDPOINT = to /<path>/api has no effect.

**Comment by benc-uk** [comment]
Yes see #24 
Sorry but I have no plans to support serving from anything other than the root path
