### ISSUE TITLE
Issue with new Kubernetes/Ingress Controller

### ISSUE THREAD

**Issue by sohnaeo** [benc-uk/kubeview#78]
Hi,

Recently, I have upgraded to new Kubernetes v1.21.5 and ingress controller. After deploying the kubeview, pods are appearing in grey color , green/red colors are missing in the gui if we access the kubeview URL. It seems kubeview cant scrap the ingresses and can see the below in the logs

 eW0927 02:08:34.821764       1 warnings.go:67] extensions/v1beta1 Ingress is deprecated in v1.14+, unavailable in v1.22+; use networking.k8s.io/v1 Ingress
2021/09/27 02:08:36 ### 10.243.166.2 GET /api/scrape/smoketest

I believe kubeview is scrapping through the ingresses through the old API extensions/v1beta, am not sure

**Comment by benc-uk** [comment]
Should be fixed in 0.1.30 https://github.com/benc-uk/kubeview/releases/tag/0.1.30
