### ISSUE TITLE
Some elements are greyed out

### ISSUE THREAD

**Issue by apgapg** [benc-uk/kubeview#80]
I have 2 projects with kubeview, 
in one of them I see all green healthy pods, but in another I see some are greyed out and deployment icons are missing.
I cannot draw any reason so as to why this is occurring in one project and not other (both projects are identical just environment is different)

Version: v0.1.11 (Helm chart)
<img width="846" alt="Screenshot 2021-10-27 at 9 31 32 AM" src="https://user-images.githubusercontent.com/13887407/138998081-42ea6d46-2dc4-4d79-bc75-f327cb713ad6.png">

**Comment by benc-uk** [comment]
Should be fixed in 0.1.30 https://github.com/benc-uk/kubeview/releases/tag/0.1.30
