### ISSUE TITLE
No Instruction for installation?

### ISSUE THREAD

**Issue by vahid-rms** [benc-uk/kubeview#90]
I cannot find any instructions on how to install the tool!
I'm using Windows. It would be great if you add more clarification on the installation process. I don't even know where to start. Here and on youtube, there is much more focus on the demo, rather than facilitating the installation process (for different platforms).

**Comment by benc-uk** [comment]
Install it into your Kubernetes cluster, using Helm
https://github.com/benc-uk/kubeview/tree/master/charts

There's no need to cover the install for different platforms as it runs in Kubernetes not on your local machine
